name: Docker Image CI

on:
  schedule:
    - cron: "* * * * *"
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASS: ${{ secrets.DOCKER_PASS }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: docker build . --file Dockerfile -t lokeshb003/text-summarizer:latest

    - name: Login to DockerHub
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASS

    - name: Push to DockerHub
      run: docker push lokeshb003/text-summarizer:latest

    - name: Notify on Success
      if: success()
      uses: rtCamp/action-slack-notify@v2
      with:
        status: 'Success'
        fields: repo,message,commit,author,workflow,job,took
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
